# Generated by Django 4.0.6 on 2022-11-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='compleated',
        ),
    ]
