# Generated by Django 4.0.6 on 2022-11-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='have_size',
            field=models.BooleanField(default=False),
        ),
    ]
