# Generated by Django 4.0.6 on 2022-11-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_orderitem_have_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='have_size',
        ),
    ]
