# Generated by Django 4.0.6 on 2022-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productcard_has_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_size', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Size',
            new_name='ShoeSize',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='size',
            new_name='shoe_size',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='has_size',
            new_name='is_cloth',
        ),
        migrations.RenameField(
            model_name='shoesize',
            old_name='size',
            new_name='shoe_size',
        ),
        migrations.AddField(
            model_name='productcard',
            name='is_shoe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cloth_size',
            field=models.ManyToManyField(blank=True, null=True, to='products.clothsize'),
        ),
    ]
