# Generated by Django 4.0.6 on 2022-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_clothsize_rename_size_shoesize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothsize',
            name='cloth_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
