# Generated by Django 4.0.6 on 2022-11-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_size',
            field=models.BooleanField(default=False),
        ),
    ]
