# Generated by Django 4.1.4 on 2023-01-06 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_order_has_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cloth_size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shoe_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cloth_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.clothsize'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shoe_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shoesize'),
        ),
    ]
