# Generated by Django 4.1.4 on 2023-02-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_clothsize_cloth_size_alter_shoesize_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothsize',
            name='cloth_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cloth_size',
            field=models.ForeignKey(blank=True, default='S', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.clothsize'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shoe_size',
            field=models.ForeignKey(blank=True, default=36.0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shoesize'),
        ),
        migrations.AlterField(
            model_name='shoesize',
            name='shoe_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
