# Generated by Django 4.1.4 on 2023-02-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_clothsize_cloth_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cloth_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.clothsize'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shoe_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shoesize'),
        ),
    ]
